name: Auto Update Sports IPTV

on:
  schedule:
    - cron: '0 2 * * *'  # 每天凌晨 2 点 UTC（北京时间 10 点）自动执行
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run update script
        run: |
          python update_sports_m3u.py

      - name: Commit & Force Push
        run: |
          git config user.name "GitHub Action"
          git config user.email "action@github.com"
          git fetch origin main
          git reset --hard origin/main
          git add sports_playlist.m3u
          git commit -m "Auto update IPTV at $(date +'%Y-%m-%d %H:%M:%S')" || echo "No changes"
          git push origin main
