name: Auto Update Sports IPTV

on:
  schedule:
    - cron: '0 2 * * *'  # 每天凌晨2点UTC（北京时间10点）更新
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    - name: Run update script
      run: |
        python update_sports_m3u.py

    - name: Commit & Push
      run: |
        git config user.name "GitHub Action"
        git config user.email "action@github.com"
        git add sports_playlist.m3u
        git commit -m "⏰ 自动更新体育直播源 $(date +'%Y-%m-%d %H:%M:%S')" || echo "No changes"
        git push
